# Generated by Django 6.0.3 on 2026-03-15 02:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category's display name.", max_length=25, unique=True)),
                ('slug', models.SlugField(blank=True, help_text="Auto-generated URL-friendly identifier based on category's name.", max_length=25, unique=True)),
                ('description', models.TextField(blank=True, help_text='(Optional) Description of category and its products.')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the tag.', max_length=25, unique=True)),
                ('slug', models.SlugField(blank=True, help_text="Auto-generated URL-friendly identifier based on tag's name.", max_length=25, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the product.', max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, help_text="Auto-generated URL-friendly identifier based on product's name.", unique=True)),
                ('description', models.TextField(help_text='Description of product. Include related and keywords, used for search.')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base retail price of product, in CAD, before any discounts.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Active discount as a percentage (e.g. 25.00 for 25% off base price).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the product was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of when the product was last modified')),
                ('category', models.ForeignKey(help_text='Category the product belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
                ('tags', models.ManyToManyField(blank=True, help_text='(Optional) Any tags the product may have for labeling & filtering', related_name='products', to='products.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
