# Generated by Django 6.0.3 on 2026-03-15 03:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_updated_products_created_at_with_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of when the product was last modified'),
        ),
    ]
